/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import com.google.gson.Gson;
import java.io.*;
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getQuoteFromFile());
    }

    public String getQuoteFromFile() {
        Gson gson = new Gson();
        Reader file = null;
        try {
            file = new FileReader("src/main/resources/recentquotes.json");
        } catch(Exception e) {
            // Ignore
        }
        Quotes quotes[] = gson.fromJson(file, Quotes[].class);
        Random rand = new Random();
        return quotes[rand.nextInt(quotes.length)].getText();
    }
}

